# Generated by rust2rpm 21
%bcond_without check

%global crate cipo

Name:           rust-%{crate}
Version:        0.1.0
Release:        %autorelease
Summary:        Crypto in, power out

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/cipo
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Crypto in, power out.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE target/package/cipo-0.1.0/LICENSE
%doc README.md
%{_bindir}/cipo

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
